name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          args: --check src/**/*.ts
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Run test coverage command
        run: deno test -A --coverage="coverage"
      - name: Upload Code coverage
        uses: codecov/codecov-action@v2
